# Generated by Django 5.2.1 on 2025-05-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_listing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
